name: player_town
description: PlayerTown Parlour Application
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  json_annotation: ^3.0.0
  google_maps_flutter: ^0.5.21

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.2.3

flutter:

  uses-material-design: true

  assets:
    - images/
